<script lang="ts">
	import { slide } from 'svelte/transition';
	let showQuickStart = false;
	let showFullDocumentation = false;
	let showChangelog = false;
</script>

<div class="mx-auto rounded p-8 shadow-md xl:w-5/6">
	<h2 class="pb-4 text-2xl font-semibold text-gray-900">Documentation</h2>
	<div class="flex flex-col justify-between gap-4">
		<div class="min-w-full rounded border border-slate-200">
			<div class="my-auto flex min-w-full flex-row justify-between rounded border bg-slate-100 p-2">
				<span class="my-auto inline-block text-xl font-bold">Quick Start</span>
				<button
					type="button"
					aria-label="Toggle quick start"
					on:click={() => (showQuickStart = !showQuickStart)}
					class={showQuickStart
						? 'rounded bg-red-500 px-4 py-2 font-bold text-white hover:bg-red-700 hover:shadow-lg'
						: 'rounded bg-yellow-300 px-4 py-2 font-bold text-slate-900 shadow-md hover:bg-yellow-500 hover:shadow-lg'}
				>
					{#if showQuickStart}Close{:else}Open{/if}
				</button>
			</div>
			{#if showQuickStart}
				<div transition:slide={{ duration: 300 }} class="bg-slate-50 p-2">
					<p class="mb-2">
						This step-by-step tutorial will let IsoQuaC analyze your labeled LC-MS/MS proteomics
						differential expression experiment and provide you with output files on both the
						non-redundant-peptide level as well as protein level, including a quality control and
						differential expression report in PDF format.
					</p>
					<ol class="ml-4 list-decimal">
						<li>
							<div class="flex flex-col">
								<span
									>You'll need the <b>peptide-spectrum matches in .txt, .csv/tsv or .xlsx format</b
									>. These should be in separate files: one per LC-MS/MS run. Please
									<b
										>verify that all required data 'observables' or 'columns' are present in your
										PSM files</b
									> and have valid contents, especially if you're not using files generated by Proteome
									Discoverer (PD).</span
								>
								<ul class="ml-4 list-disc">
									<li>
										<span class="font-bold">Sequence</span>: {'{'}string{'}'} the peptide sequence
									</li>
									<li>
										<span class="font-bold">Master Protein Accessions</span>: {'{'}string;string;...{'}'}
										accession numbers of the proteins associated with a PSM. separated by semi-colons.
									</li>
									<li>
										<span class="font-bold">First Scan</span>: {'{'}integer{'}'} identifier for the MS
										scan in which the peptide was detected.
										<i
											>If you don't have such a column, just create one with all values set to a
											unique integer. PSMs detected by multiple times by different PSM Algorithms
											should have the same value.</i
										>
									</li>
									<li>
										(???): {'{'}string{'}'} names of the reporter labels or channel names you provided
										in the DoE file.
									</li>
								</ul>
								<p>
									If this is not the case, simply create a text file (<strong>wrapper</strong>) with
									on each line YOUR_NAME for the observable, as well as OUR_NAME, separated by a TAB
								</p>
								<p>
									If you have any additional columns or observables you would like IsoQuaC to use,
									please refer to the complete set of compatible column names.
								</p>
							</div>
						</li>
						<li>
							<div class="mt-4">
								<p>
									You'll also need a <strong>'design of experiment' (DoE) file</strong>. Create one
									by going to the &quot;New DoE&quot; page and following the instructions. You'll
									have to give names to your different 'LC-MS/MS runs', specify which
									biological/chemical conditions were used in which MS run, and indicate for each MS
									run which 'channels' or 'reporter labels' (as they appear in the headers of your
									PSM files) belong to which of those conditions. At the end of the procedure, you
									can download the DoE file you need. This file can easily be modified with a text
									editor if you want to correct a mistake, or quickly generate your own new DoE
									file.
								</p>
							</div>
						</li>
						<li>
							<div class="mt-4">
								<p>
									Got your PSM files and DoE file? Great, in the <strong
										>&quot;New Job&quot; form</strong
									>, choose a job name. Then, upload your DoE file.
								</p>
							</div>
						</li>
						<li>
							<div class="mt-4 flex flex-col">
								<p>Fill out the <strong>Job Settings form</strong>. Please remark:</p>
								<ul class="ml-4 list-disc">
									<li>
										If you are not using Proteome Discoverer for generating PSM files, you will be
										warned to provide the wrapper file(s) you (should have) created in the PSM file
										verification step by uploading one under the &quot;Advanced&quot; button for
										each PSM data file.
									</li>
									<li>
										In case you used multiple search engines to generate PSMs, the information from
										the Master engine will be preferred over that of the Slave(s).
									</li>
									<li>
										IsoQuaC will refrain from using 'shared peptides' (peptides that may correspond
										to multiple proteins) unless you check the box under &quot;Advanced
										settings&quot;. In that case a second analysis will be done for the assuming
										that all proteins make (full) use of every peptide they share with another
										protein.
									</li>
								</ul>
							</div>
						</li>
						<li>
							<div class="mt-4">
								<p>
									Press <strong>&quot;Submit job&quot;</strong> and make sure you land on the &quot;Job
									Info&quot; page which states your job is running. If you didn't provide an e-mail address,
									be sure to copy and save the job ID. You can use your job ID to retrieve your job information
									from the &quot;Find job&quot; page in case you close your Job Info page.
								</p>
							</div>
						</li>
						<li>
							<div class="mt-4 flex flex-col">
								<p>
									As soon as the job is done, the Job Info page will provide you with download links
									for the report file as well a .zip file containing:
								</p>
								<ul class="ml-4 list-disc">
									<li>
										normalized data on the non-redundant, modified peptide level (1 file per
										LC-MS/MS run)
									</li>
									<li>
										differential expression analysis on the protein level (in 1 comprehensive file
										as well as split out in 1 file per condition)
									</li>
								</ul>
							</div>
						</li>
					</ol>
				</div>
			{/if}
		</div>
		<div class="min-w-full rounded border border-slate-200">
			<div class="my-auto flex min-w-full flex-row justify-between rounded border bg-slate-100 p-2">
				<span class="my-auto inline-block text-xl font-bold">Full documentation</span>
				<button
					aria-label="Toggle full documentation"
					type="button"
					class={showFullDocumentation
						? 'rounded bg-red-500 px-4 py-2 font-bold text-white hover:bg-red-700 hover:shadow-lg'
						: 'rounded bg-yellow-300 px-4 py-2 font-bold text-slate-900 shadow-md hover:bg-yellow-500 hover:shadow-lg'}
					on:click={() => (showFullDocumentation = !showFullDocumentation)}
				>
					{#if showFullDocumentation}Close{:else}Open{/if}
				</button>
			</div>
			{#if showFullDocumentation}
				<div transition:slide={{ duration: 300 }} class="flex flex-col gap-8 bg-slate-50 p-2">
					<div>
						<p>
							Here you can find the scientific description as well as <a
								class="text-blue-600 underline visited:text-purple-600 hover:text-blue-800"
								href="#reqs">prerequisites</a
							>
							and
							<a
								class="text-blue-600 underline visited:text-purple-600 hover:text-blue-800"
								href="#techspecs">technical specifications</a
							>
							of the IsoQuaC workflow, which runs on a server located at
							<a
								class="text-blue-600 underline visited:text-purple-600 hover:text-blue-800"
								href="https://uhasselt.be">UHasselt</a
							>
							and is accessible through a
							<a
								class="text-blue-600 underline visited:text-purple-600 hover:text-blue-800"
								href="https://isoquac.net">web interface</a
							>.
						</p>
						<p class="mt-4 mb-2">The scientific workflow consists of three distinct steps:</p>
						<ul class="ml-4 list-decimal">
							<li>
								<a class="link font-bold" href="#processing">Processing</a>: cleans the input data
								while gathering some QC information, and aggregates the PSMs to the modified,
								non-redundant peptide level, then performs normalization.
							</li>
							<li class="mt-2">
								<a class="link font-bold" href="#analysis">Analysis</a>: while gathering additional
								QC information, transforms the information from the peptide to the protein level and
								performs a differential expression analysis (DEA). Also performs an exploratory
								analysis for quality control (QC) purposes, including a principal component analysis
								(PCA) and hierarchical clustering (HC) on the peptide-level data matrix.
							</li>
							<li class="mt-2">
								<a class="link font-bold" href="#reporting">Reporting</a>: produces a PCA plot
								(first 2 components), HC dendrogram and for each non-reference condition a volcano
								plot with a list of the top differential proteins. From the gathered QC info,
								produces some statistics and MS1 calibration and intensity plots if possible.
								Lastly, Summarizes all visualizations, statistics and other relevant information
								(including meta-data) into a PDF report.
							</li>
						</ul>
						<p class="mt-4">
							The output for the user contains the created report, as well as some tab-separated
							(.tsv) data files:
						</p>
						<ul class="mt-1 ml-4 list-disc">
							<li>
								normalized data on the non-redundant, modified peptide level (1 file per LC-MS/MS
								run)
							</li>
							<li class="mt-2">
								differential expression analysis on the protein level (in 1 comprehensive file as
								well as split out in 1 file per condition)
							</li>
						</ul>
						<p class="mt-4">
							If you wish to acquire any intermediate output files, please <a
								class="text-blue-600 underline visited:text-purple-600 hover:text-blue-800"
								href="#contact">contact us</a
							>.
						</p>
						<p class="mt-4">
							Most of the parameters which control the behaviour of the workflow are fixed when
							using the web interface. If you wish to run a job with a custom set of parameters,
							please <a
								class="text-blue-600 underline visited:text-purple-600 hover:text-blue-800"
								href="#contact">contact us</a
							>.
						</p>

						<div class="mt-2">
							<figure class="mt-2 mb-2">
								<img src="isoquac_docu_schema.png" alt="IsoQuaC workflow overview" />
								<figcaption>
									<p>
										IsoQuaC workflow overview.
										<span style="color:red">Red: main input/output and workflow backbone.</span>
										<span style="color:blue">Blue: optional input/output and workflow steps.</span>
										<span style="color:green"
											>Green: input and workflow steps directly influenced by user-specifiable
											parameters.
										</span>
										<span style="color:grey">Grey: currently disabled.<span> </span></span>
									</p>
								</figcaption>
							</figure>
						</div>
					</div>
					<div>
						<p class="text-xl font-bold" id="reqs">Prerequisites</p>
						<p class="my-2">The following requirements are to be met in order to use IsoQuaC:</p>
						<ul class="ml-4 list-disc">
							<li>
								This workflow was built for <b>labeled shotgun proteomics</b> with TMT-labeled
								N-plex peptide samples eluted through a liquid chromatography column, then ionised,
								then selected for m/z value by an MS1 and then further fragmented to be quantified
								by an MS2. However, it also works for experiments based on equivalent techniques,
								f.i. iTRAQ labeling, and it has been shown (publication pending) to also work for
								<b>Next-Gen Sequencing (NGS)</b> count data, f.i. raw RNA-Seq counts.
							</li>
							<li class="mt-2">
								The MS2 spectra of the mass spectrometer should have already been analyzed and
								converted into <b>peptide-spectrum matches (PSMs)</b>, for instance using one or
								multiple database search algorithms like, for instance, SEQUEST
								<i class="font-sm">[DOI: 10.1016/1044-0305(94)80016-2]</i>
								or MASCOT
								<i class="font-sm"
									>[DOI: 10.1002/(SICI)1522-2683(19991201)20:18{'<'}3551::AID-ELPS3551{'>'}3.0.CO;2-2]</i
								>.
							</li>
							<li class="mt-2">
								In case multiple samples belonging to the same condition are spread across multiple
								LC-MS/MS runs, make sure that <b
									>the samples belonging to the same condition are always evenly spread across all
									the LC-MS/MS runs they appear in</b
								>.<br />
								Do <u>not</u>, f.i., put 5 samples of condition A and 1 of condition B in the first
								LC-MS/MS run, and then 1 sample of condition A and 5 of condition B in the second.
								Rather, you should respect intelligent experimental design and spread the samples so
								that each run contains 3 samples of each condition.
							</li>
							<li class="mt-2">
								IsoQuaC normalises the data through an iterative proportional fitting procedure
								(IPFP). The normalisation can be verified on an MA-plot of your peptide- or
								protein-level data:
								<ul class="mt-2 ml-8 list-decimal">
									<li>
										<strong
											>The majority of proteins/peptides are not differentially expressed</strong
										>, to avoid a bias in the estimate of the mean value. It is assumed that up-down
										shifts are not due to biological causes. The reference set used in the
										normalization step is the set of all peptides identified in the experiment.
										<br /><em
											>MA-plot: the observations form a single &#39;cloud&#39; with a dense center
											and less dense edges, as opposed to, for instance, two clouds or a cloud with
											uniform density.</em
										>
									</li>
									<li class="mt-2">
										<strong
											>The number of up-regulated proteins/peptides is roughly equal to the number
											of down-regulated ones</strong
										>. If the data were skewed, this would lead to a bias in the normalization
										result.
										<br /><em
											>MA-plot: the cloud of observations exhibits a bilateral symmetry about some
											axis (usually horizontal, but not necessarily).</em
										>
									</li>
									<li class="mt-2">
										<strong
											>The systematic bias in each sample&#39;s quantification signal intensity is
											linearly proportional to the magnitude of the intensity</strong
										>. Only this way it is possible to find one appropriate normalization factor for
										each quantification sample.
										<br /><em
											>MA-plot: the axis of bilateral symmetry is a straight line (which may be
											inclined), i.e., the moving average M-values of the central cloud form a
											straight line.</em
										>
									</li>
								</ul>
							</li>
							<li class="mt-2">We recommend using non-transformed intensities as input values.</li>
						</ul>
					</div>
					<div>
						<p class="text-xl font-bold" id="processing">Processing</p>
						<p class="my-2">
							The input data files are PSM files, preferrably exported from Proteome Discoverer (PD)
							2.1, although it is perfectly possible to use different platforms as long as the data
							complies to the
							<a
								class="text-blue-600 underline visited:text-purple-600 hover:text-blue-800"
								href="#inputspecs">specifications</a
							>. They can be represented as tables (one for each LC-MS/MS run) where each row
							represents a unique PSM corresponding to a peptide observation, containing the
							observed values of the variables/quantities described by the column headers.
						</p>
						<p>
							The following steps process the data into a human-readabe format at the peptide level
							that is ready for interpretation by the data analysis part of the workflow. Relevant
							parameters from the processing configuration file (automatically generated by the web
							interface) are in <code>teletype font</code>. Column header or variable names are
							<em>italicized</em>.
						</p>
						<ul class="mt-2 ml-8 list-decimal">
							<li>
								Read the PSM data file into a Pandas data frame, apply the <a
									class="text-blue-600 underline visited:text-purple-600 hover:text-blue-800"
									href="#wrapper">wrapper</a
								> and load the processing configuration parameters.
							</li>
							<li class="mt-2">
								Remove obsolete (non-wanted) columns/variables. <code>wantedColumns</code>.
							</li>
							<li class="mt-1">
								Information about regular <em>Protein Accessions</em> and their corresponding
								information in the <em>Protein Descriptions</em> strings are removed; only the information
								about master proteins is kept.
							</li>
							<li class="mt-1">
								Remove PSMs that have missing values in <code>noMissingValuesColumns</code>, or that
								have missing values in all of the <code>quanColumns</code>.
							</li>
							<li class="mt-1">
								Remove PSMs with <em>Confidence</em> levels worse than
								<code>removeBadConfidence_minimum</code>.
								<code>removeBadConfidence_bool</code>.
							</li>
							<li class="mt-1">
								Remove PSMs with <em>Isolation Interference [%]</em> levels higher than
								<code>removeIsolationInterference_threshold</code>.
								<code>removeIsolationInterference_bool</code>.
							</li>
							<li class="mt-1">
								Clean PTM information by keeping only the PTM identities, not their locations, and
								removing all &#39;TMT&#39; label modifications. The remaining PTMs are then sorted
								alphabetically.
							</li>
							<li class="mt-1">
								Remove redundancy due to the use of multiple <code>PSMEnginePriority</code> PSM
								detection algorithms, which are specifiable by the user.
								<code>removePSMEngineRedundancy_bool</code>. If a peptide observation yielded more
								than one PSM (one for each algorithm) then we only keep the PSM of the PSM engine
								with the highest priority, and the others are removed.<!--Peptide observations yielding only one PSM are discarded if they were not
                            discovered by the Master algorithm. <code>removePSMEngineRedundancy_exclusive_bool</code>.-->
							</li>
							<li class="mt-1">
								(Currently unavailable) Correct isotopic impurities, see <a
									class="text-blue-600 underline visited:text-purple-600 hover:text-blue-800"
									href="#IIC">Isotope impurity correction</a
								>.
							</li>
							<li class="mt-1">
								Aggregate on retention time <em>RT [min]</em> (RT), see
								<a
									class="text-blue-600 underline visited:text-purple-600 hover:text-blue-800"
									href="#aggregate">Aggregating duplicate observations</a
								>.
								<code>aggregateRT_bool</code>,
								<code>aggregate_method</code>.
							</li>
							<li class="mt-1">
								Aggregate on <em>Charge</em> if possible, see
								<a
									class="text-blue-600 underline visited:text-purple-600 hover:text-blue-800"
									href="#aggregate">Aggregating duplicate observations</a
								>.
								<code>aggregateCharge_bool</code>, <code>aggregate_method</code>.
							</li>
							<li class="mt-1">
								Aggregate on post-translational <em>Modifications</em> (PTMs) (Disabled by default)
								if possible, see <a href="#aggregate">Aggregating duplicate observations</a>.
								<code>aggregatePTM_bool</code>, <code>aggregate_method</code>.
							</li>
							<li class="mt-1">
								Perform the IPFP normalization, see <a
									class="text-blue-600 underline visited:text-purple-600 hover:text-blue-800"
									href="#normalization">normalization</a
								>.
							</li>
							<li class="mt-1">Save all results to disk and pass them on to the analysis step.</li>
						</ul>
						<p class="mt-2">
							For all removed data, at least the columns specified by
							<code>removalColumnsToSave</code> are saved – sometimes together with more information
							relevant at a certain removal step – into either one file for all removal steps or
							into separate files per removal step, as specified by
							<code>removedDataInOneFile</code>.
						</p>
						<div>
							<p class="mt-4 font-bold">Aggregating duplicate observations</p>
							<p class="my-2">
								Removing redundancy in the list of PSMs due is what we call aggregating. This is
								necessary to avoid artificial enrichment by counting the same peptide multiple times
								in the DEA. We consider three possible variables that cause redundancy, which we may
								aggregate on:
							</p>
							<ul class="mt-2 ml-8 list-decimal">
								<li>
									RT (<code>aggregateRT_bool</code>): depending on the data-dependent acquisition
									(DDA) settings of the MS, it forgets the peptides previously detected by the MS1
									after a fixed time interval t<sub>DDA</sub>
									(i.e. after each <em>MS1 sweep</em>) and possibly detects the same peptide
									multiple times at different RT values, if it takes longer than t<sub>DDA</sub> to elute
									from the LC column.
								</li>
								<li class="mt-2">
									Charge (<code>aggregateCharge_bool</code>): the electrospray ionization is a
									stochastic process which may place zero or more than one positive charge on each
									peptide. Since the MS cannot distinguish peptides but only m/z values, the same
									peptide can be detected multiple times (with different charge values) even within
									the same MS1 sweep.
								</li>
								<li class="mt-2">
									PTM (<code>aggregatePTM_bool</code>): just as charge influences the m/z value, so
									does the mass of the peptide being detected by the MS1. As a peptide may carry
									modifications – either multiple TMT labels or biologically relevant modifications
									like phosphorylation – it may thus appear with different mass values and be
									detected multiple times even within the same MS1 sweep. Please note that on the
									peptide level we use the PTM information as-is. Since PD includes PTM location
									information, this means that the same ligand in a different location is considered
									a different PTM. On the protein level (later in the workflow), the N-terminal TMT
									label modifications as well as any PTM location information are filtered out.
								</li>
							</ul>
							<p class="mt-2">
								The aggregations on charge and/or PTM are optional in theory, but are specified by
								their respective boolean parameters. By default Charge aggregation is enabled
								(unless the corresponding column is missing from the data frame) and PTM aggregation
								is disabled. The aggregation on RT is mandatory, as we assume its variability is
								never of biological importance. It is always executed, even if the &#39;RT
								[min]&#39; column does not exist as we assume RT to be the only other source of
								redundancy. Therefore, there should be no additional properties causing peptide
								sequence redundancy in your data set, except for the use of multiple <code
									>PSMEnginePriority</code
								>.
							</p>
							<p class="mt-2" id="aggregatemethod">
								For each aggregation a representative PSM is chosen. This representative is added to
								the data frame and the representees are removed. It contains all the information of
								the representee that had the best PSM score, except for the quantification values.
								The best PSM score is the best score calculated by the Master PSM algorithm, if
								available, or otherwise the best score calculated by (one of) the Slave
								algorithm(s), if available, or if no score is available the program just takes the
								information of the first representee encountered. The quantification values of the
								representative can be determined in one of three ways, specified by <code
									>aggregate_method</code
								>:
							</p>
							<ul class="mt-2 ml-8 list-decimal">
								<li>
									{'{'}bestMatch{'}'}: the quantification values of the PSM with the best PSM score
									(see above). In case all PSMs have missing scores, the most intense is chosen
									instead (see below).
								</li>
								<li class="mt-2">
									{'{'}mostIntense{'}'}: the quantification values of the PSM with the highest sum
									of its MS2 quantification values.
								</li>
								<li class="mt-2">
									{'{'}mean{'}'}: the value for each quantification sample is the mean of the
									quantification values of all representees for that same quantification sample.
								</li>
								<li class="mt-2">
									{'{'}geometricMedian{'}'}: the components of the <em>quantification vector</em>
									that is the geometric mean of the quantification vectors of the representees, where
									the quantification vectors are vectors in Euclidian N-space with their &#8467;<sub
										>1</sub
									>-norm set to 1 and with the (re-scaled) quantification values as its components.
									To calculate the geometric median, we use the algorithm developed by Vardi et al.
									(DOI: 10.1073/pnas.97.4.1423).
								</li>
							</ul>
							<p class="mt-2">
								Note that the only information carried by a representative that is (currently) also
								used in the downstream analysis, is the information identical for the corresponding
								representees (like the peptide sequence) – except for the quantification values
								about which we have just elaborated.
							</p>
							<p class="mt-2">
								Any data that has been removed at any point can be saved to a &#39;removed data
								collection&#39; which may be used by the IsoQuaC team only anonymously and only for
								meta-analysis purposes.
							</p>
						</div>
						<div>
							<p class="mt-4 font-bold" id="IIC">
								<em>(disabled)</em> Isotope impurity correction <a name="IIC"></a>
							</p>
							<p class="mt-2">
								<em>This functionality is currently disabled.</em>
								Provided with the isotope impurity matrix (not the TMT-style format), one can easily calculate
								the true quantification values from the observed ones by just solving the linear system
								of equations as explained by Shadforth et al. (DOI: 10.1186/1471-2164-6-145). Of course
								this requires one to know the observed quantification values for all of the PSM peaks
								that receive a contribution from reporter isotopes, and those may not always appear at
								the same m/z-values as the other labels and hence will not be available in the PD2.1 output
								(if PD2.1 did not apply the correction itself).
							</p>
						</div>
						<div>
							<p class="mt-4 font-bold" id="normalization">IPFP Normalization</p>
							<p class="mt-2">
								The normalisation is based on an iterative proportional fitting procedure (IPFP),
								where the mean-values of the rows and the columns of the data matrix are fitted to
								the value of one. IPFP is also commonly referred to as the RAS-procedure or
								raking-procedure. Through normalisation, systematic biases in the data are corrected
								for all peptides across a sample. The algorithms makes two assumptions:
							</p>
							<ul class="mt-2 ml-8 list-disc">
								<li class="mt-2">The relative nature of the quantification values</li>
								<li class="mt-2">The equimolarity of the samples</li>
							</ul>
							<p class="mt-2">
								If P if the number of peptides and N the number of samples, we want to impose two
								constraints to transform the unnormalized P × N matrix A that contains the
								quantification values, into a normalized matrix K that does obey these constraints.
								The first constraint is that the values of each row must sum to N (relative
								quantification) and on the other hand that the values of each column must sum to P
								(equimolarity).
							</p>
							<p class="mt-2">
								To reach convergence for K, we could infinitely iterate. Ofcourse, this is not
								feasible and therefore one can never guarantee K to be obtained exactly since we are
								restricted to our assumptions. IPFP has been shown to have a monotonically
								converging entropy, &#8467;<sub>1</sub>-measure and likelihood. We define the
								precision after iteration i as N/2 × |R<sub>i</sub><sup>−1</sup> − I<sub>P</sub> |; the
								number of columns divided by two, times the total deviation of the matrix with row means
								from the P × P identity matrix. Note that after each iteration, the deviation of the column
								means is of course exactly zero. The convergence of this algorithm – and thus also the
								precision improvement – is exponential in the number of iterations, and in fact the convergence
								is asymptotically identical.
							</p>
							<p class="mt-2">
								If there happen to be missing values in the quantification matrix A, we just
								calculate the <code>numpy.nanmean</code> instead of the mean. This function from the
								Python package <code>numpy</code>
								ignores any missing values in the calculation of the mean, so a row with one missing value
								now has a sum of (N − 1) . However, the mean value for the normalized quantification values
								in that row will still be 1 and the algorithm needs no further adaptations.
							</p>
						</div>
					</div>
					<div>
						<p class="text-xl font-bold" id="analysis">Analysis</p>
						<p class="mt-2">
							After the processing steps have been performed for each MS run individually, the
							quantification values are normalized and the data is ready for analysis.
						</p>
						<p class="mt-2">
							During the analysis steps some metadata is also extracted, some of which will be shown
							in the report file and some of which is kept by the IsoQuaC team but may only be used
							anonymously and only for meta-analysis purposes.
						</p>
						<p class="mt-2">
							The necessary ingredients to make visualizations of the DEA and Quality Control and a
							report in general are calculated and extracted in the following steps in the two
							sections below. Relevant parameters from the processing configuration file
							(automatically generated by the web interface) are in <code>teletype font</code>.
							Column header or variable names are <em>italicized</em>.
						</p>

						<div>
							<p class="mt-4 font-bold" id="DE">Differential Expression</p>
							<ol class="mt-2 ml-8 list-decimal">
								<li>
									Combine the data frames of all MS runs into one data frame by performing an
									&#39;outer join&#39;: simply a vertical concatenation but with the quantification
									columns of each MS run kept separate, still retaining their distinct names. In
									this way, peptides with the same <em>Sequence</em> can appear multiple times (will be
									considered a repeated measurement), but no peptide of one MS run has any values in the
									quantification columns corresponding to other MS runs (those values are &#39;missing&#39;).
								</li>
								<li class="mt-2">
									Use latter combined data frame to compile a mapping – across all MS runs – between
									the proteins found and their respective peptides. This can be done in two ways
									because some peptides may possibly correspond to more than one (master) protein,
									even though the proteins have already been grouped:
									<ul class="ml-8 list-disc">
										<li>
											Each protein gets contributions only from non-shared peptides: they are
											uniquely associated to that protein. <code>minExpression_bool</code>
										</li>
										<li>
											Each protein gets the full contribution from all peptides that are associated
											with it, even if they are in reality shared with other proteins.
											<code>fullExpression_bool</code>
										</li>
									</ul>
									We refer to the former as the ‘minimal expression’ case, and to the latter as the ‘full
									expression’ case. The minimal expression cannot be disabled by the user, but the user
									may enable the full expression which is by default not performed.
								</li>
								<li class="mt-2">
									Execute the peptide-protein mappings according to previously mentioned dictionary,
									to obtain a data frame on the protein level. For each protein entry the data frame
									contains the protein description, the list of (representative) peptides and the
									list of corresponding quantification values, split into one column for each
									condition.
								</li>
								<li class="mt-2">
									Perform a <a
										class="text-blue-600 underline visited:text-purple-600 hover:text-blue-800"
										href="#detest">DE test</a
									> for each protein using a moderated t-test with Benjamini-Hochberg correction. The
									p-values and Benjamini-Hochberg adjusted p-values are added to the protein-level data
									frame.
								</li>
								<li class="mt-2">
									Calculate for each protein and each condition the log<sub>2</sub> fold change
									w.r.t. the reference condition <code>referenceCondition</code> specified by the
									user. Parameter (<code>pept2protCombinationMethod</code>) specifies whether the
									mean or the median of the quantification values is used to calculate the fold
									change between the two lists of peptides. End-users cannot change the default
									which is to use the mean.
								</li>
								<li class="mt-2">
									Calculate the DEA significance indicator for each protein:
									<ul class="ml-8 list-disc">
										<li>yes (both the p-value and fold change are significant)</li>
										<li>p (only the p-value is significant)</li>
										<li>fc (only the fold change is significant)</li>
										<li>no (neither the p-value nor the fold change are significant)</li>
									</ul>
									where the p-value and fold change significance thresholds are specified by
									<code>alpha</code>
									(significant means p \&lt; <code>alpha</code>) and <code>FCThreshold</code>
									(significant means log<sub>2</sub>(condition/reference) >
									<code>FCThreshold</code>), respectively.
								</li>
								<li class="mt-2">
									Save all results to disk and pass them on to the Report &amp; visualization
									procedure.
								</li>
							</ol>
							<p class="mt-4 font-bold" id="detest">DE test: moderated t-test</p>
							<p class="mt-2">
								We would like to perform a <a
									class="text-blue-600 underline visited:text-purple-600 hover:text-blue-800"
									href="https://doi.org/10.1016/j.euprot.2015.02.002">moderated t-test</a
								> (as used in limma for RNA-seq) for each protein between the quantification values of
								the reference condition and each other condition to see whether their means differ. In
								order to do this, for each protein we first average its associated peptide quantifications
								within the same sample because they are repeated measurement, and then for each condition
								pool the values of all associated samples, across all MS runs. This does mean we are not
								using all available information, which impacts statistical power, but exploiting that
								information requires a mixed model approach. We explicitly do not want to employ an approach
								using linear mixed models, as it is a cumbersome and time-consuming procedure for a data
								set with a few thousand proteins.
							</p>
							<p class="mt-2">
								To control the false discovery rate – and not the family-wise error rate, as the
								Bonferroni correction does – we employ the Benjamini-Hochberg correction and obtain
								adjusted p-values.
							</p>
							<p class="mt-2">
								When calculating the mean quantification value per condition for a certain protein
								over all its measurements, we have to take the <code>nanmean</code> to ignore missing
								values. In the case that there is just one value available for both conditions under consideration,
								the result of the (moderated) t-test is nonsensical and this protein is removed from the
								data frame after all.
							</p>
						</div>
						<div>
							<p class="mt-4 font-bold">Quality Control</p>
							<ul class="mt-2 ml-4 list-decimal">
								<li>
									Combine only the quantification and <em>Sequence</em> columns of the data frames
									of all MS runs into one data frame, but this time as an &#39;inner join&#39; on
									the peptide sequence. This way, only peptides observed in at least one sample of
									each MS run are present. They occur only once, and they only have missing values
									in quantification columns (which are all still distinguishable) if they were not
									detected in the corresponding sample. The result is a data frame with each unique
									peptide sequence that was found at least one in each condition across all MS runs.<!-- because peptides with LESS than one measurement for each condition were ALREADY filtered out, thus presence in an
                            MS run automatically implies presence in each condition.-->
								</li>
								<li class="mt-2">
									Perform a Principal Component Analysis (PCA) and Hierarchical Clustering (HC) on
									the transpose of the quantification matrix associated with the data frame from the
									previous step. Missing values will be imputed to be 0, because PCA and HC cannot
									handle them and zero- imputation does make sense in this situation. After all, the
									missing values that now remain are not due to a peptide not being present in a
									certain MS run or condition (because such entries have been removed during the
									construction of this data frame). That means they are missing quite probably
									because they are actually zero, or just very small (so that they did not meet the
									detection threshold). Therefore we deem this zero-imputation justified.
								</li>
								<li class="mt-2">
									Save all results to disk and pass them on to the Report &amp; visualization
									procedure.
								</li>
							</ul>
							<p class="mt-4 font-bold" id="pca">Principal component analysis</p>
							<p class="mt-2">
								Performing a principal component analysis involves calculating the single-value
								decom- position (SVD) of the transposed quantification matrix across all the MS
								runs, which is of size P<sub>c</sub> × <code>sum of all N<sub>i</sub></code> , where
								P<sub>c</sub> is the amount of peptides found at least once in all MS runs and
								conditions, and N<sub>i</sub> is the amount of samples in MS run i. The standard
								<code>matplotlib</code>
								function is rather slow for a matrix of this size, and therefore we will use the custom
								SVD method described by Halko et al. (DOI: 10.1137/090771806) and borrow an
								<a
									class="text-blue-600 underline visited:text-purple-600 hover:text-blue-800"
									href="https://github.com/scikit-learn/scikit-learn/blob/babe4a5d0637ca172d47e1dfdd2f6f3c3ecb28db/scikits/learn/utils/extmath.py#L105"
									>open source implementation from GitHub</a
								>. Only the first two PCs are extracted.
							</p>
							<p class="mt-4 font-bold">Hierarchical clustering</p>
							<p class="mt-2">
								A hierarchical clustering is performed on the transposed quantification matrix
								across all MS runs, so that each sample represents an observation and each peptide
								quantification is an observable (just like with the PCA). As a linkage criterium
								UPGMA (mean linkage) was used, together with a Euclidian metric.
							</p>
						</div>
					</div>
					<div>
						<p><a class="text-xl font-bold" id="reporting">Reporting</a></p>
						<p class="mt-2">
							The Report & visualization step takes the protein-level data frames with differential
							expression results, the PCA and HC results as well as other QC information and plots,
							the meta-data and application log file as input for the following steps.
						</p>
						<ul class="mt-2 ml-8 list-decimal">
							<li>
								For each DE test, calculate a list of significantly (according to adjusted p-value)
								differentially expressed proteins, sorted according to adjusted p-value. For each
								protein, also provide the description, log2 fold change, adjusted p-value and total
								amount (before averaging repeated measurements) of supporting peptides observed. If
								both minimally and fully expressed protein data frames are given, create two lists
								of mutually exclusive proteins and add it to the meta-data for a consecutive
								sensitivity analysis.
							</li>
							<li class="mt-2">
								For each DE test, make a volcano plot of the minimal and/or full data frame, with
								coloring accord- ing to significance level (see <a
									class="text-blue-600 underline visited:text-purple-600 hover:text-blue-800"
									href="#significant">last step of DE</a
								>), and with the protein IDs indicated for all data points of the significance
								levels specified by
								<code>labelVolcanoPlotAreas</code>. End-users cannot change this behavior and by
								default only data points with a &#39;yes&#39; significance level are labeled.
							</li>
							<li class="mt-2">
								Make a PCA plot, which is a 2D scatterplots of the first (horizontal axis) and
								second (vertical axis) principal component scores, where data points are colored
								according to condition and with different marker symbols for each MS run. The units
								on the axes bear no meaning other than dimensionless similarity measures.
							</li>
							<li class="mt-2">
								Make a HC Dendrogram plot, which is a dendrogram displaying the results of the
								hierarchical clustering, where singletons are colored according condition. The
								length of the dendrogram lines indicate the Euclidean distance between two leaves,
								although they bear no meaning other than a dimensionless similarity measure.
							</li>
							<li class="mt-2">
								Make an MS1 calibration plot, which is a scatterplot of the PSMs&#39; relative
								(w.r.t. the maximum) PSM Engine Scores versus their &quot;DeltaM [ppm]&quot; value.
								Information from each tandem-MS run is plotted in a different color.
							</li>
							<li class="mt-2">
								Make an MS1 intensity histogram, which shows the amount of detected PSMs in function
								of their MS1 intensity. A histogram including information from only those PSMs
								actually used by IsoQuaC (i.e. not discarded for some reason).
							</li>
							<li class="mt-2">
								Generate a HTML report using flask, which contains the volcano plot(s), PCA plot, HC
								plot, list of top n differential proteins (sorted on adjusted p-value and with n
								specified by numDifferentials) and meta-data, possibly with additional info from the
								log file.
							</li>
							<li class="mt-2">
								Generate a PDF report from the HTML file and create a .zip-file with the DEA data
								frames in .tsv-format for each non-reference condition.
							</li>
							<li class="mt-2">
								Return all output files from the previous step to the web interface, which will
								display them on the front-end as well as e-mail them.
							</li>
						</ul>
						<p class="mt-2">
							The PCA plot and HCD serve as quality control tools, as they give the user an
							immediate impression of the influence of a sample belonging to a certain condition as
							opposed to belonging to a certain MS run. If the normalization was successful <em
								>and</em
							>
							there are sufficient differences between the conditions, one ought to see samples grouped
							together per condition (and not per MS run or some other criterium).
							<br />Also, when the samples corresponding to a certain condition are spread across
							multiple MS runs, one could be worried that one particular sample is – for whatever
							reason, biological or accidental or statistical – not like all the other samples that
							belong to the same condition, which would distort the true statistics. However if such
							an anomaly were to occur, it would be visible from the PCA and/or HC plot.
						</p>
					</div>
					<div>
						<p class="text-xl font-bold" id="techspecs">Technical Specifications</p>
						<div>
							<p class="mt-2 font-bold" id="inputspecs">Input file formats</p>
							<p class="mt-2">
								The workflow requires the following input files. The ones to be uploaded by the user
								are marked with (U), the others are automatically generated when using the web
								interface.
							</p>
							<ul class="mt-2 ml-8 list-disc">
								<li>
									(U) a <a
										class="text-blue-600 underline visited:text-purple-600 hover:text-blue-800"
										href="#doespecs">Design of Experiments (DoE)</a
									> file (can also be created using the web interface);
								</li>
								<li>
									(U) one <a
										class="text-blue-600 underline visited:text-purple-600 hover:text-blue-800"
										href="#PSMfiles">PSM quantification data file</a
									> per MS run (PD produces the right format);
								</li>
								<li>
									(U) (optional) a <a
										class="text-blue-600 underline visited:text-purple-600 hover:text-blue-800"
										href="#wrapper">wrapper file</a
									> when using custom data headers.
								</li>
								<li>
									one processing configuration file per MS run with the QCQuan processing settings;
								</li>
								<li>
									a job configuration file, auto-generated by the web interface based a.o. on some
									user-specified settings;
								</li>
								<li>
									<em>(currently not available; optional)</em> a file with the isotope impurities in matrix
									or TMT table format.
								</li>
							</ul>
							<p class="mt-4 font-bold" id="doespecs">Design of Experiments file</p>
							<p>
								This file is supposed to be uploaded by the user, who may create one from scratch or
								by using the <a
									class="text-blue-600 underline visited:text-purple-600 hover:text-blue-800"
									href="{'{'}{'{'}url_for('doe.create')}}">DoE creator</a
								>. The schema of the experimental setup is a tab-separated text file (.tsv or
								tabular .txt) with a layout like the example shown in the table below. For each
								separate tandem-MS run a name is be specified which will function as a prefix if no
								quanColumn aliases are provided (see further).
							</p>
							<table class="documentation-table mt-4 table min-w-full table-auto border-collapse">
								<thead class="bg-slate-300">
									<tr>
										<th class="border border-slate-900">MS run name</th>
										<th class="border border-slate-900">Condition:quanColumns:aliases</th>
										<th class="border border-slate-900">Condition:quanColumns:aliases</th>
										<th class=" border border-slate-900">...</th>
									</tr>
								</thead>
								<tbody>
									<tr class="text-center">
										<td>TMT8_tuesday</td>
										<td>mouse:126,127:m1,m2</td>
										<td>human:128,129:h1,h2</td>
										<td>...</td>
									</tr>
									<tr class="text-center">
										<td>iTRAQ8_2</td>
										<td>human:114,115:h3,h4</td>
										<td>mouse:116,117:</td>
										<td>...</td>
									</tr>
									<tr class="text-center">
										<td>...</td>
										<td>...</td>
										<td>...</td>
										<td>...</td>
									</tr>
								</tbody>
							</table>
							<p class="mt-4">
								For each MS run one can specify an arbitrary number of conditions, which do
								<em>not</em> have to be in the same column of the DoE file in case the same
								condition appears in multiple MS runs. Each condition entry - which corresponds to
								one field in the file / table - is formatted as follows: first the name of the
								condition, followed by a colon, followed by a comma-separated list of all data frame
								quantification column names, optionally followed by a colon, optionaly followed by a
								comma-separated list of aliases for those quantification column names (in the same
								order). These quantification column names and corresponding aliases will be
								automatically appended to the
								<a
									class="text-blue-600 underline visited:text-purple-600 hover:text-blue-800"
									href="#wrapper">wrapper file</a
								>, so there is no need to add them manually.
								<br />If no aliases are specified, the aliases are automatically generated to be the
								original names prefixed by the MS run&#39;s name and an underscore symbol. For
								instance, for the second condition of the iTRAQ8_2 MS run in the example table, the
								generated aliases would be &#39;iTRAQ8_2_mouse_116&#39; and
								&#39;iTRAQ8_2_mouse_117&#39;.
							</p>
							<p class="mt-4 font-bold" id="PSMfiles">PSM files (quantification data)</p>
							<p class="mt-2">
								The PSM files (maximum combined size: 75MB, can be changed on request) may be
								formatted as .xlsx (Microsoft Office), .csv (comma-separated), .tsv (tab-separated)
								or .txt (custom delimiter) files. By default, Proteome Discoverer (PD) produces tab-
								separated .txt files, and its PSM output files have names suffixed with “PSMs”
								should meet all requirements specified above. If you are using a different platform,
								read this section carefully and also take a look at the <a
									class="text-blue-600 underline visited:text-purple-600 hover:text-blue-800"
									href="#altusers">quick fixes</a
								> in case you are unsure about how to proceed.
							</p>
							<p class="mt-2">
								The following columns/quantities are <strong
									>absolutely required in each data file</strong
								> and should not contain missing values (the corresponding detections/rows will be discarded).
							</p>
							<table class="documentation-table mt-4 table min-w-full table-auto border-collapse">
								<thead>
									<tr class="bg-slate-300">
										<th class="border border-slate-900">Column name</th>
										<th class="border border-slate-900">Type</th>
										<th class="border border-slate-900">Details</th>
									</tr>
								</thead>
								<tbody>
									<tr class="text-center">
										<td><strong>Sequence</strong></td>
										<td>string</td>
										<td
											>The raw peptide sequence as a sequence of 1-letter amino-acid
											representations, without modifications or any other annotations.</td
										>
									</tr>
									<tr class="text-center">
										<td><strong>Master Protein Accessions</strong></td>
										<td>string; string; ...</td>
										<td
											>UNIPROT identifiers of the proteins associated with a PSM, separated by
											&#39;; &#39; (semi-colon and space). The master protein is the representative
											protein of choice for a whole protein group to which a peptide may correspond,
											as provided by PD2.1.</td
										>
									</tr>
									<tr class="text-center">
										<td><strong>First Scan</strong></td>
										<td>integer</td>
										<td
											>Identifier for the MS scan in which the peptide was detected. <em
												>If you don&#39;t have such a column, just create one with all values set to
												a unique integer.</em
											></td
										>
									</tr>
									<tr class="text-center">
										<td><strong>&lt;quantification<br />columns></strong> </td>
										<td>float</td>
										<td
											>Column names: channel names you provided in the DoE file. <br />Values:
											Quantification values (strictly positive; zeros are replaced by NaN). We
											recommend using non-transformed intensities. Do not use log2(ratio) values.</td
										>
									</tr>
								</tbody>
							</table>
							<p class="mt-4">
								The above list also includes the names of the reporter quantification samples
								present in your data, although only one of them is required to contain an actual
								non-missing value in order not to be discarded. One can use either PD's intensities
								or S/N values as quantification values, since QCQuan can handle both and we find
								they produce practically indistinguishable results.
							</p>
							<p class="mt-2">
								The following columns/quantities are <strong
									>only required under the circumstances mentioned</strong
								> and should in that case not contain missing values (the corresponding detections/rows
								will be discarded):
							</p>
							<table class="documentation-table table min-w-full table-auto border-collapse">
								<thead>
									<tr class="bg-slate-300">
										<th class="border border-slate-900">Column name</th>
										<th class="border border-slate-900">Type</th>
										<th class="border border-slate-900">Details</th>
									</tr>
								</thead>
								<tbody>
									<tr class="text-center">
										<td><strong>Identifying Node Type</strong></td>
										<td>Mascot; Sequest HT; ...</td>
										<td
											>(algorithm used to generate the PSM) if you used multiple PSM scoring
											algorithms.</td
										>
									</tr>
									<tr class="text-center">
										<td><strong>Charge</strong></td>
										<td>integer</td>
										<td
											>(charge of the precursor ion) if you wish to avoid aggregation on Charge (see <a
												href="#aggregate">Processing aggregation step</a
											>) or do not care about missing values.</td
										>
									</tr>
									<tr class="text-center">
										<td><strong>Modifications</strong></td>
										<td>string: mod1; mod2; ...</td>
										<td
											>(Chemical modifications present on the peptide sequence) if you wish to avoid
											aggregation on Modifications (see <a
												class="text-blue-600 underline visited:text-purple-600 hover:text-blue-800"
												href="#aggregate">Processing aggregation step</a
											>) or do not care about missing values. The format should be a single string,
											suing &#39;;&#39; as a separator between multiple modifications. Information
											outside parentheses () is excluded automatically (e.g. PTM location
											information in the PD format).</td
										>
									</tr>
									<tr class="text-center">
										<td><strong>Protein Accessions</strong></td>
										<td>string</td>
										<td
											>(Uniprot identifiers of all matching protein according to the ‘Identifying
											Node’) if you wish to have a &#39;descriptions&#39; column in your DEA output
											with Master Protein Descriptions;</td
										>
									</tr>
									<tr class="text-center">
										<td><strong>Protein Descriptions</strong></td>
										<td>string</td>
										<td
											>(Uniprot description of each matching protein) if you wish to have a
											&#39;descriptions&#39; column in your DEA output with Master Protein
											Descriptions;</td
										>
									</tr>
									<tr class="text-center">
										<td><strong>XCorr</strong>/<strong>Ions Score</strong>/... </td>
										<td>float</td>
										<td
											>(SEQUEST/MASCOT/... PSM score) if using ‘bestMatch’ as the <code
												>aggregate_method</code
											>
											value (see <a href="#aggregate">Processing aggregation step</a>) and used
											SEQUEST/MASCOT/... to calculate PSMs, or if you wish to get MS1 calibration QC
											plot;</td
										>
									</tr>
									<tr class="text-center">
										<td><strong>Confidence</strong></td>
										<td>string: Low, Medium, High</td>
										<td
											>(confidence level of the PSM identification) if you wish (<code
												>removeBadConfidence_bool</code
											>) to filter out PSMs with low confidence values (<code
												>removeBadConfidence_minimum</code
											>);</td
										>
									</tr>
									<tr class="text-center">
										<td><strong>Isolation Interference [%]</strong></td>
										<td>float</td>
										<td
											>(measure for the relative amount of co-isolation) if you wish (<code
												>removeIsolationInterference_bool</code
											>) to filter out PSMs with high isolation interference values (<code
												>removeIsolationInterference_threshold</code
											>).</td
										>
									</tr>
									<tr class="text-center">
										<td><strong>DeltaM [ppm]</strong></td>
										<td>float</td>
										<td
											>(MS1 mass error) if you wish to get QC information w.r.t. the error on the
											precursor ion mass.</td
										>
									</tr>
									<tr class="text-center">
										<td><strong>Ion Inject Time [ms]</strong></td>
										<td>float</td>
										<td
											>(necessary MS2 ion accumulation time) if you wish to get QC information
											w.r.t. the necessary MS2 ion accumulation time.</td
										>
									</tr>
								</tbody>
							</table>
							<p class="mt-4 font-bold" id="altusers">Other platforms</p>
							<p class="mt-2">
								At this moment QCQuan is not really vendor-neutral, but we aspire to make it so. In
								the meanwhile, the following non-exhaustive list of suggestions may provide users
								with quick fixes so they can use the workflow even with different platforms:
							</p>
							<ul class="mt-2 ml-8 list-disc">
								<li>
									use a <a
										class="text-blue-600 underline visited:text-purple-600 hover:text-blue-800"
										href="#wrapper">wrapper file</a
									> to automatically transform column headers and increase your ease-of-use;
								</li>
								<li>
									if your PSMs do not have information about the first scan number, fake this column
									and fill it with unique integers;
								</li>
								<li>
									if your PSMs do not have information about charge or modifications, fake these
									columns and fill them with zeroes or empty strings, respectively; <strong
										class="error">Caution</strong
									>: do not fill them with &quot;None&quot; or &quot;N/A&quot; strings or
									equivalent, as they will then be interpreted as missing values.
								</li>
								<li>
									if your PSM algorithm does not provide PSM scores, fake a score column filled with
									zeroes;
								</li>
								<li>
									if your PSM algorithm provides positive scores where ‘lower’ means ‘better’,
									negate all scores.
								</li>
							</ul>
							<p class="mt-4 font-bold" id="wrapper">Wrapper file</p>
							<p class="mt-2">
								The optional wrapper file is simply a .tsv- or tab-separated .txt-file with two
								columns that map original variable names (first column) onto new ones (second
								column). Each line thus contains both a variable name from the user&#39;s custom
								data file and a new name – which ought to be one from the list specified by the <code
									>wantedColumns</code
								>
								parameter (see next section) – separated by a tab character.
								<br />The quantification column names and corresponding aliases from the
								<a
									class="text-blue-600 underline visited:text-purple-600 hover:text-blue-800"
									href="#doespecs">DoE file</a
								> will be automatically extracted and appended to the wrapper, so there is no need to
								add them manually.
							</p>
							<p class="mt-4 font-bold" id="procconf">Processing Configuration file</p>
							<p class="mt-2">
								Each processing configuration file contains the settings to be used in the
								corresponding Processing step and is generated automatically when using the web
								interface. Such files are .ini files which contains only a <code>[DEFAULT]</code>
								section and which is read using a ConfigParser from the configparser module, with options
								<code>allow_no_values=True</code>, <code>comment_prefixes=’;’</code> and
								<code>inline_comment_prefixes=’@’</code>. All possible parameters are listed in the
								table below, although
								<strong>none of these settings can be explicitly changed by the end-user</strong>.
							</p>
							<table class="documentation-table mt-4 table min-w-full table-auto border-collapse">
								<thead>
									<tr class="bg-slate-300">
										<th class="border border-slate-900">Parameter name</th>
										<th class="border border-slate-900">default; other values</th>
										<th class="border border-slate-900">Details</th>
									</tr>
								</thead>
								<tbody>
									<tr>
										<td><code>data</code></td>
										<td></td>
										<td
											>Path on disk to the <a
												class="text-blue-600 underline visited:text-purple-600 hover:text-blue-800"
												href="#PSMfiles">quantification data file</a
											>. Auto-generated by the web interface from the DoE file.</td
										>
									</tr>
									<tr>
										<td><code>delim_in</code></td>
										<td>\t</td>
										<td
											>When uploading .txt files, it is advisable to explicitly specify the
											delimiter used, although the workflow does a pretty good job at auto-detecting
											it.</td
										>
									</tr>
									<tr>
										<td><code>wrapper</code></td>
										<td></td>
										<td
											>Path on disk to the <a
												class="text-blue-600 underline visited:text-purple-600 hover:text-blue-800"
												href="#wrapper">wrapper file</a
											>. Auto-generated by the web interface from the DoE file.</td
										>
									</tr>
									<tr>
										<td><code>quanColumns</code></td>
										<td></td>
										<td
											>Columns headers of the quantification values. Auto-generated by the web
											interface from the experimental setup schema.</td
										>
									</tr>
									<tr>
										<td><code>wantedColumns</code></td>
										<td
											>[&quot;Confidence&quot;, &quot;Identifying Node Type&quot;,
											&quot;Sequence&quot;, &quot;Modifications&quot;, &quot;Master Protein
											Accessions&quot;, &quot;Protein Accessions&quot;, &quot;# Protein
											Groups&quot;, &quot;Protein Descriptions&quot;, &quot;m/z [Da]&quot;,
											&quot;Charge&quot;, &quot;Deltam/z [Da]&quot;, &quot;Isolation Interference
											[%%]&quot;, &quot;RT [min]&quot;, &quot;First Scan&quot;]; [custom]</td
										>
										<td
											>List of columns that are extracted from the PSM data files. All other columns
											are removed. This step happens <em>after</em> the wrapper has been applied.
											The <code>quanColumns</code> are automatically appended by the web interface.</td
										>
									</tr>
									<tr>
										<td><code>requiredColumns</code></td>
										<td
											>[&quot;First Scan&quot;, &quot;Sequence&quot;, &quot;Master Protein
											Accessions&quot;]; [custom]</td
										>
										<td
											>List of columns which are absolutely required for the workflow to complete
											successfully. The <code>quanColumns</code> are automatically appended by the web
											interface.</td
										>
									</tr>
									<tr>
										<td><code>noMissingValuesColumns</code></td>
										<td
											>[&quot;First Scan&quot;, &quot;Sequence&quot;, &quot;Identifying Node
											Type&quot;, &quot;Master Protein Accessions&quot;, &quot;Charge&quot;,
											&quot;Modifications&quot;]; [custom]</td
										>
										<td
											>List of columns in which no missing values may appear. If a missing value is
											found, the corresponding row is removed. The
											<code>quanColumns</code> are automatically appended by the web interface.
										</td>
									</tr>
									<tr>
										<td><code>removalColumnsToSave</code></td>
										<td
											>[&quot;First Scan&quot;, &quot;Sequence&quot;, &quot;Identifying Node
											Type&quot;, &quot;Master Protein Accessions&quot;]; [custom]</td
										>
										<td
											>List of columns to save to disk whenever data is removed from the data frame
											for any reason (except during <a
												class="text-blue-600 underline visited:text-purple-600 hover:text-blue-800"
												href="#aggregate">Aggregation</a
											>). The <code>quanColumns</code> are automatically appended by the web interface.
											This information will only ever be used (anonymously) for meta-analysis purposes.</td
										>
									</tr>
									<tr>
										<td><code>aggregateColumnsToSave</code></td>
										<td
											>[&quot;First Scan&quot;, &quot;Sequence&quot;, &quot;Identifying Node
											Type&quot;, &quot;RT [min]&quot;, &quot;Charge&quot;,
											&quot;Modifications&quot;, &quot;Master Protein Accessions&quot;,
											&quot;Degeneracy&quot;]; [custom]</td
										>
										<td
											>List of columns to save to disk whenever data is removed from the data frame
											during <a
												class="text-blue-600 underline visited:text-purple-600 hover:text-blue-800"
												href="#aggregate">Aggregation</a
											>. The
											<code>quanColumns</code> are automatically appended by the web interface. This information
											will only ever be used (anonymously) for meta-analysis purposes.
										</td>
									</tr>
									<tr>
										<td><code>removeBadConfidence_bool</code></td>
										<td>true; false</td>
										<td
											>Remove PSMs with ‘Confidence’ lower than
											<code>removeBadConfidence_minimum</code>.
										</td>
									</tr>
									<tr>
										<td><code>removeBadConfidence_minimum</code></td>
										<td>Medium; High; Low</td>
										<td
											>PSMs with ‘Confidence’ lower than this value are removed if so specified by <code
												>removeBadConfidence_bool</code
											></td
										>
									</tr>
									<tr>
										<td><code>removeIsolationInterference_bool</code> </td>
										<td>true</td>
										<td
											>Remove PSMs with ‘Isolation interference [%]’ lower than
											<code>removeIsolationInterference_threshold</code>.
										</td>
									</tr>
									<tr>
										<td>
											<code>removeIsolationInterference_threshold</code>
										</td>
										<td>30; float between 0 and 100</td>
										<td
											>2 PSMs with ‘Isolation interference [%]’ higher than this value are removed
											if so specified by removeIsolationInterference_bool</td
										>
									</tr>
									<tr>
										<td><code>PSMEnginePriority</code></td>
										<td></td>
										<td
											>String-encoded Python dictionary of PSM detection algorithms and their score
											column names used while removing redundancy due to the use of multiple PSM
											algorithms/engines. They are ordered according to priority (lower list index
											means higher priority).</td
										>
									</tr>
									<tr>
										<td><code>PSMEnginePriority</code>: engineNames</td>
										<td>[unspecified]; [Mascot, Sequest HT]], [custom, custom, ...], ...</td>
										<td
											>Names of PSM algorithms/engines, ordered according to priority (lower list
											index means higher priority). If set to &quot;unspecified&quot;, the workflow
											assumes there is no PSM Algorithm information available and <code
												>removePSMEngineRedundancy_bool</code
											> has no effect.</td
										>
									</tr>
									<tr>
										<td><code>PSMEnginePriority</code>: scoreNames</td>
										<td>[unspecified]; [Ions Score, XCorr], [custom, custom, ...], ...</td>
										<td
											>Score columns names corresponding to the list of PSM algorithms/engines, in
											the same order.</td
										>
									</tr>
									<tr>
										<td><code>removePSMEngineRedundancy_bool</code></td>
										<td>true; false</td>
										<td
											>Remove redundancy due to the use of multiple PSM algorithms. Behavior of the
											workflow with value &#39;false&#39; has not been tested.</td
										>
									</tr>
									<tr>
										<td>
											<code>removePSMEngineRedundancy_exclusive_bool</code>
										</td>
										<td>false; true</td>
										<td
											>Controls whether only PSMs detected by the master algorithm should be kept.</td
										>
									</tr>
									<tr>
										<td
											><em>(Currently disabled)</em>
											<code>isotopicCorrection_bool</code>
										</td>
										<td>false</td>
										<td
											>Perform <a
												class="text-blue-600 underline visited:text-purple-600 hover:text-blue-800"
												href="#IIC">isotopic correction</a
											> using isotopicCorrection_matrix or not.</td
										>
									</tr>
									<tr>
										<td
											><em>(Currently disabled)</em>
											<code>isotopicCorrection_matrix</code>
										</td>
										<td></td>
										<td
											>Path to the isotope impurity matrix. Auto-generated by the web interface
											after uploading an <a
												class="text-blue-600 underline visited:text-purple-600 hover:text-blue-800"
												href="#ICfile">isotope impurity file</a
											>.</td
										>
									</tr>
									<tr>
										<td><code>aggregate_method</code></td>
										<td>bestMatch; mostIntense, mean, geometricMedian </td>
										<td
											>The method specifying <a
												class="text-blue-600 underline visited:text-purple-600 hover:text-blue-800"
												href="#aggregatemethod">how to combine quantification values</a
											> of multiple representee PSMs.</td
										>
									</tr>
									<tr>
										<td><code>aggregateRT_bool</code></td>
										<td>true; false</td>
										<td>Remove redundancy due to different retention times.</td>
									</tr>
									<tr>
										<td><code>aggregateCharge_bool</code></td>
										<td>true; false</td>
										<td>Remove redundancy due to different charge states.</td>
									</tr>
									<tr>
										<td><code>aggregatePTM_bool</code></td>
										<td>false; true</td>
										<td>Remove redundancy due to different post-translational modifications.</td>
									</tr>
									<tr>
										<td><code>precision</code></td>
										<td>10<sup>-5</sup>; float</td>
										<td
											>Desirable precision of the <a
												class="text-blue-600 underline visited:text-purple-600 hover:text-blue-800"
												href="#constand">CONSTANd algorithm</a
											>.</td
										>
									</tr>
									<tr>
										<td><code>maxIterations</code></td>
										<td>50; integer &gt; 0</td>
										<td
											>Maximum number of iterations of the <a
												class="text-blue-600 underline visited:text-purple-600 hover:text-blue-800"
												href="#constand">CONSTANd algorithm</a
											>.</td
										>
									</tr>
									<tr>
										<td><code>removedDataInOneFile_bool</code></td>
										<td>false; true</td>
										<td
											>If enabled, saves all data frames with information about removed data in
											separate files.</td
										>
									</tr>
									<tr>
										<td><code>path_out</code></td>
										<td></td>
										<td
											>Path on disk to save output files to. Auto-generated by the web interface
											from the experimental setup schema.</td
										>
									</tr>
									<tr>
										<td><code>filename_out</code></td>
										<td>result</td>
										<td>Auto-generated by the web interface from the experimental setup schema.</td>
									</tr>
									<tr>
										<td><code>delim_out</code></td>
										<td>\t</td>
										<td>Text delimiter used when writing Processing output to disk.</td>
									</tr>
								</tbody>
							</table>
							<p class="mt-4 font-bold">Job configuration file</p>
							<p class="mt-2">
								The job configuration file contains the settings to be used in the corresponding
								Analysis and Report steps and is generated automatically when using the web
								interface, in which case only the parameters marked with (U) can be adjusted by the
								user. It is a .ini file which contains only a <code>[DEFAULT]</code> section and
								which is read using a ConfigParser from the configparser module, with options
								<code>allow_no_values=True</code>, <code>comment_prefixes=’;’</code> and
								<code>inline_comment_prefixes=’@’</code>. All possible parameters are listed below,
								together with their {'{'}default values; other possible values{'}'} and descriptions.
							</p>
							<table class="documentation-table mt-4 table min-w-full table-auto border-collapse">
								<thead class="bg-slate-300">
									<tr>
										<th class="border border-slate-900">Parameter name</th>
										<th class="border border-slate-900">default; other values</th>
										<th class="border border-slate-900">Details</th>
									</tr>
								</thead>
								<tbody>
									<tr>
										<td>date</td>
										<td>now</td>
										<td
											>Full Python datetime (%Y-%m-%d %H:%M:%S.%f) at upload of DoE file,
											auto-generated by the web interface.</td
										>
									</tr>
									<tr>
										<td><a href="#schemastruct">schema</a></td>
										<td></td>
										<td
											>String-encoded Python dictionary containing the DoE information as well as
											some additional meta-information. Auto-generated by the web interface from the
											experimental setup schema and uploaded files.</td
										>
									</tr>
									<tr>
										<td>getRTIsolationInfo_bool</td>
										<td>false, true</td>
										<td
											>If enabled, gathers RT isolation statistics during the RT <a
												href="#aggregate">Aggregation step</a
											> and stores it in metadata. This information will only ever be used (anonymously)
											for meta-analysis purposes.
										</td>
									</tr>
									<tr>
										<td>pept2protCombinationMethod</td>
										<td>mean; median</td>
										<td
											>Central measure to generate one quantification value for a protein from a
											list of peptide quantification values when calculating fold changes for the <a
												href="#DE">DEA</a
											>.</td
										>
									</tr>
									<tr>
										<td>minExpression_bool</td>
										<td>true; false</td>
										<td>Do a <a href="#DE">DEA</a> for the minimally expressed set of proteins.</td>
									</tr>
									<tr>
										<td>(U) fullExpression_bool</td>
										<td>false; true</td>
										<td>Do a <a href="#DE">DEA</a> for the fully expressed set of proteins.</td>
									</tr>
									<tr>
										<td>(U) referenceCondition</td>
										<td></td>
										<td
											>Name of the condition to be used as the reference in the
											<a href="#DE">DEA</a>.
										</td>
									</tr>
									<tr>
										<td>alpha</td>
										<td>0.05; float between 0 and 1</td>
										<td
											>Significance level for the differential expression&#39;s moderated t-test.</td
										>
									</tr>
									<tr>
										<td>FCThreshold</td>
										<td>1; float &gt; 0</td>
										<td
											>Threshold above which a fold change value is considered significant in th <a
												href="#DE">DEA</a
											>.</td
										>
									</tr>
									<tr>
										<td>labelVolcanoPlotAreas</td>
										<td>[true, false, false, false]; ...</td>
										<td
											><a href="#significant">Significance levels</a>
											whose proteins to label with their protein IDs. Order: [‘yes’, ‘p’, ‘fc’, ‘no’].</td
										>
									</tr>
									<tr>
										<td>PCA_components</td>
										<td>2; integer &isin; {'{'}2..amount of conditions{'}'}</td>
										<td
											>Number of principal components to be extracted in the <a href="#PCA">PCA</a
											></td
										>
									</tr>
									<tr>
										<td>(U) numDifferentials</td>
										<td>10; integer &gt; 0</td>
										<td>Number of top differentially expressed proteins to show in the report.</td>
									</tr>
									<tr>
										<td>(U) jobname</td>
										<td></td>
										<td
											>Name of the job, specified by the user. Will be appended to the timestamp to
											form the job ID.</td
										>
									</tr>
									<tr>
										<td>path_out</td>
										<td></td>
										<td>Path on disk to where output files ought to be saved. </td>
									</tr>
									<tr>
										<td>(U) delim_out</td>
										<td>\t; any character</td>
										<td>Text delimiter used when writing Analysis and Report output to disk.</td>
									</tr>
									<tr>
										<td>jobID</td>
										<td>date_jobname</td>
										<td
											>Concatenation of job date and job name with underscore separator.
											Auto-generated by web interface.</td
										>
									</tr>
									<tr>
										<td>(U) mailRecipient</td>
										<td></td>
										<td>E-mailadress to which output and job status updates are sent.</td>
									</tr>
								</tbody>
							</table>
							<p class="mt-4 font-bold" id="schemastruct">Schema structure</p>
							<p class="mt-2">
								The schema in the table above is a String-encoded, nested Python dictionary with the
								key-value structure shown below, where 'channel' is synonymous for 'quantification
								column'.
							</p>
							<table class="documentation-table mt-4 table min-w-full table-auto border-collapse">
								<thead class="bg-slate-300">
									<tr>
										<th class="border border-slate-900">Key</th>
										<th class="border border-slate-900">Value / Nested Key</th>
										<th class="border border-slate-900">...</th>
										<th class="border border-slate-900">...</th>
									</tr>
								</thead>
								<tbody>
									<tr>
										<td>allMSRuns</td>
										<td>[MS runs]</td>
										<td></td>
										<td></td>
									</tr>
									<tr>
										<td>allConditions</td>
										<td>[conditions]</td>
										<td></td>
										<td></td>
									</tr>
									<tr>
										<td>MSRun</td>
										<td>allMSRunConditions</td>
										<td>[conditions]</td>
										<td></td>
									</tr>
									<tr>
										<td></td>
										<td>allMSRunChannelNames</td>
										<td>[channelNames]</td>
										<td></td>
									</tr>
									<tr>
										<td></td>
										<td>allMSRunChannelAliases</td>
										<td>[channelAliases]</td>
										<td></td>
									</tr>
									<tr>
										<td></td>
										<td>config</td>
										<td>path</td>
										<td></td>
									</tr>
									<tr>
										<td></td>
										<td>data</td>
										<td>path</td>
										<td></td>
									</tr>
									<tr>
										<td></td>
										<td>wrapper</td>
										<td>path</td>
										<td></td>
									</tr>
									<tr>
										<td></td>
										<td>isotopicCorrection_matrix</td>
										<td>(disabled) path</td>
										<td></td>
									</tr>
									<tr>
										<td></td>
										<td>{'{'}conditions{'}'}</td>
										<td>channelNames</td>
										<td>[names]</td>
									</tr>
									<tr>
										<td></td>
										<td></td>
										<td>channelAliases</td>
										<td>[aliases]</td>
									</tr>
									<tr>
										<td></td>
										<td>{'{'}...}</td>
										<td>{'{'}...}</td>
										<td>[...]</td>
									</tr>
								</tbody>
							</table>
							<p class="mt-4 font-bold" id="ICfile"><em>(disabled)</em> Isotope impurities file</p>
							<p class="mt-2">
								For each data file one may optionally specify the isotope impurities using another
								.tsv- file. This file may either contain a matrix (used directly by the workflow) or
								a TMT-style formatted table (IDT) that is automatically transformed into the correct
								matrix by the web interface. In the former case this is a tab-separated isotope
								impurity matrix (IIM). In the latter case the format is also tabular, resembling the
								format used in the Thermo Fisher's COA documents and with the string “IDT” as the
								columns header for the sample names.
							</p>
						</div>
					</div>
					<div id="contact" class="pt-2">
						<p class="text-xl font-bold">Contact us</p>
						<i class="pt-2"
							>Contact us through: <a
								class="text-blue-600 underline visited:text-purple-600 hover:text-blue-800"
								href="mailto:isoquac@uhasselt.be">isoquac@uhasselt.be</a
							></i
						>
					</div>
				</div>
			{/if}
		</div>
		<div class="min-w-full rounded border border-slate-200">
			<div class="my-auto flex min-w-full flex-row justify-between rounded border bg-slate-100 p-2">
				<span class="my-auto inline-block text-xl font-bold">Changelog</span>
				<button
					aria-label="Toggle full changelog"
					type="button"
					class={showChangelog
						? 'rounded bg-red-500 px-4 py-2 font-bold text-white hover:bg-red-700 hover:shadow-lg'
						: 'rounded bg-yellow-300 px-4 py-2 font-bold text-slate-900 shadow-md hover:bg-yellow-500 hover:shadow-lg'}
					on:click={() => (showChangelog = !showChangelog)}
				>
					{#if showChangelog}Close{:else}Open{/if}
				</button>
			</div>
			{#if showChangelog}
				<div transition:slide={{ duration: 300 }} class="flex flex-col gap-2 bg-slate-50 p-2">
					<div>
						<div class="font-bold">Version 0.10.2</div>
						<div>
							A developer version of IsoQuaC is released. We are working towards creating a new
							environment for quantitative MS-based proteomics research. The current release may
							contain several issues. Please bare with us while we solve this. If there are any
							wishes which you, as a user, would like to see implemented, please contact us! A major
							part of IsoQuaC will be working towards an ideal framework for differential expression
							analysis.
						</div>
					</div>
					<div class="pt-2">
						<i
							>Contact us through: <a
								class="text-blue-600 underline visited:text-purple-600 hover:text-blue-800"
								href="mailto:isoquac@uhasselt.be">isoquac@uhasselt.be</a
							></i
						>
					</div>
				</div>
			{/if}
		</div>
	</div>
</div>
